# Generated by Django 6.1.1 on 2026-09-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedCard',
            fields=[
                ('card_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('set_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('rarity', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('is_foil', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
