# Generated by Django 6.1.1 on 2026-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedcard',
            name='custom_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='collectedcard',
            name='market_price',
            field=models.FloatField(default=0.0),
        ),
    ]
